mongo_config:
    -   host: ''
        port: ''
        username: ''
        password: ''
        database: ''
    -   host: ''
        port: ''
        username: ''
        password: ''
        database: ''