mssql_config:
    -   server: ''
        user: ''
        password: ''
        port: 1433
        database: ''
        options:
            encrypt: true
        pool:
            max: 100
            min: 0
            idleTimeoutMillis: 60000
    -   server: ''
        user: ''
        password: ''
        port: 1433
        database: ''
        options:
            encrypt: true
        pool:
            max: 100
            min: 0
            idleTimeoutMillis: 60000